### PR TITLE
#31 - memoize returned callbacks for useTimer

### PR DESCRIPTION
**Pull request by dylanmrowe**
Tested by running/verifying the demo site locally. This will allow users to use the returned callbacks (start, pause, resume, restart) as dependencies of useEffect, useCallback, etc. without having the dependency change on every single render.

Should be fully backwards compatible with existing uses of useTimer.

Only implemented for useTimer for now. This was mainly to demonstrate the principle. I can do the others if required.

### CODE REVIEW

**Comment by dylanmrowe** [comment]
In testing this altered code further, using 'start' as a dependency of useEffect still causes infinite renders when 'restart' is also called inside that useEffect. However there are ways to work around this by not using start() at all. Calling start() is rarely useful, especially because this type of timer still ticks down in the background even when pause() is called. 

There's also a bug where calling pause() right after restart() doesn't pause the timer. Putting a timeout of 50ms or so on the pause lets it work. restart() does same state updates that need to finish before pause() will do something. (That doesn't have anything to do with this PR and probably needs a separate issue)

**Comment by chybisov** [comment]
@amrlabib could you please review and merge this?

**Review by informsharique — APPROVED** [review]

**Review by informsharique — APPROVED** [review]

**Comment by ysageev** [comment]
Has this been abandoned? Is anyone still merging PRs?  If not, fork??

**Comment by amrlabib** [comment]
Sorry for not maintaining the library. i would like to update the library and add memoized callbacks to all hooks let me know if you have time to resolve conflicts and make this PR ready anytime soon so that we can merge. Also question why we memoize onExpire ?

**Comment by amrlabib** [comment]
Done in v3.0.6

**Pull request closed without merging**
