### PR TITLE
Added Live Demos

### PR DESCRIPTION
**Pull request by jordanliu**
Issue #26

### CODE REVIEW

**Comment by jordanliu** [comment]
Review required @amrlabib

**Comment by amrlabib** [comment]
Thank you @jordanliu  for the PR, but i am not a big fan of adding external live demo links in readme file, for the following reasons:

1. These links get removed at some point and we will end up with readme referencing wrong or 404 links, it happened a lot to me
2. The hooks example is very simple and i don't think it needs a live demo
3. It is very easy to see hook running from repo by running `yarn build:dev`

Anyways thank you again

**Comment by cjke** [comment]
As a consumer it's a shame these demo's weren't merged. In the end, I have bookmarked the PR diff just so I have the links handy. 

The use of the word "consumer" is odd, but its to highlight point 3 above. Most users aren't going to navigate into their node_modules folder to run `npm run build:dev` or `yarn build:dev`. As a contributor or owner, sure, but not as a consumer. 

I think this is an excellent library and I'm using it on two different projects but... there are some sneaky edge cases that aren't explained in the readme which is why I am constantly popping open the demo's above. For example, just now, I wasn't sure if `reset` would stop the timer running _and_ set it to zero (my original assumption, which ended up being wrong). Obviously I could dig through the source and/or raise a PR to improve the docs, but sometimes its just quicker to refer to a live demo and tinker. 

At the end of the day, its your call, but I will say its common to have live demo's. I understand that your past experience suggests it's not a good idea to rely on an external demo, but how about a Storybook that sits inside the repo itself?

**Comment by amrlabib** [comment]
Thank you for your comment i was exploring a bit recently to see a good solution to have a demo that will never get removed and will always be updated, and i found a nice way to do it using github pages, you will be a able to find the library demo [here](https://amrlabib.github.io/react-timer-hook/).

This will always be updated since the demo is based on code in master, so any updates merged to master will automatically update the demo, also we are sure now that it will never be removed since it is just pointing to the repo itself, hope this will help

**Pull request closed without merging**
